//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.208
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NotificationListener
{
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NotificationActions", Namespace="http://webservices.registration.com/notification")]
    public enum NotificationActions : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOMER_REGISTERED = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOMER_UPDATED = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOMER_TRANSFERRED = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUSTOMER_DELETED = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://webservices.registration.com/notification", ConfigurationName="Listener.NotificationPortType")]
    public interface NotificationPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="*", ReplyAction="*")]
        void Notify(System.Nullable<NotificationActions> action, string reference);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NotificationPortTypeChannel : NotificationPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NotificationPortTypeClient : System.ServiceModel.ClientBase<NotificationPortType>, NotificationPortType
    {
        
        public NotificationPortTypeClient()
        {
        }
        
        public NotificationPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public NotificationPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NotificationPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NotificationPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public void Notify(System.Nullable<NotificationActions> action, string reference)
        {
            base.Channel.Notify(action, reference);
        }
    }
}
